### ISSUE TITLE
Add a placeholder image to every post

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/girlcodeapp#16]
Currently the ideas feed at feed.html displays text but no images.

Let's add a placeholder image for each idea. Every idea will have the same picture, for now. Later, In a different issue, we will let the user submit an image of their choice.

- [ ] remember to create a new branch for this ticket
- [ ] look at your Neocities website (from earlier in the Girl Code course) to see how to add an image to a webpage (or google it!)
- [ ] look at feed.html for the code that adds a new idea to the feed
- [ ] add some code to include an image inside the post

**Comment by mgatland** [comment]
no, now included in another ticket
