### ISSUE TITLE
Display each post's time more nicely in the feed i.e. "5 minutes ago"

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcodeapp#21]
In feed.html we display the time for each post, but it's not pretty.

# ACT 1

Right now, it looks like this: `2015-09-09T03:42:18.991Z`. Only good if you are a robot  🤖

We can make that nicer, but it will take a lot of code. *Fortunately, someone else has already written the code for us!* I found a plugin that will work, it's called jquery-dateFormat.

- [x] Include jquery-dateFormat by adding this line to the *head* section of feed.html

`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-dateFormat/1.0/jquery.dateFormat.js"></script>`

(It should go just below the other `<script>` line in the head section)

Now we have jquery-dateFormat, we can use some new commands. The full documentation is at https://github.com/phstc/jquery-dateFormat, but I pulled out the interesting parts for you here:

- [x] to display the post time nicely, replace `idea.dt` with this:

`$.format.prettyDate(idea.dt)`

- [x] check that your dates are now pretty! They should say something like "11 minutes ago"

This is a good time to commit your changes

# ACT 2

It's kind of confusing that the time is the same color as the text and author name.

Let's give the time its own html tag, with a class so we can give it a different CSS styles.

In feed.html, in the javascript, You will need to add an opening tag before the time, and a closing tag after the time.

- [x] Add `<div class='time'>` before the time value, and `</div>` after the time value.

Because we're writing in javascript, not in real HTML, we need to put the HTML tags inside speech marks so they become a string. (They will turn green in the Atom text editor.) Also, the string needs to be connected to the time with a plus in between.

- [x] Add a css rule to `style.css` that makes the time display in a different colour.

Check the feed to see that the time is now in a different colour.

**Comment by jlaramiranda** [comment]
its done?
