### ISSUE TITLE
make the 'like' button increase a post's like counter

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/girlcodeapp#28]
you can't do this until #23 is done

Once #23 is done, every post now has a unique ID.

# add a likes count

in index.js, when we create a new post, give it a likes count
```javascript
idea.likes = 0;
```

# Display the likes count

In `feed.html`, display each post's like count. This will be very similar to how we display each post's text, author, time (dt) and so on!

# When the like button is clicked, work out which ID matches

In feed.html, there's already code for when the like button is clicked. It starts with `ideaElement.delegate`

That code currently makes an *alert* popup. The popup has the text of the idea you chose.

- [ ] change it so instead of popping up the idea.text, it pops up the idea.id

If that works, clicking on the 'like' button should pop up a number like 1001.

Next, instead of making an *alert* pop up, we want to send a POST to the server. Here's the code:

```javascript
var data = {};
data.postId = idea.id;
$.post("/liked", data);
```

protip: POST is when you want to change something on the server. GET is when you want the server to tell you something.

Now we need to go to `index.js` and teach it how to respond to a new kind of POST.

Start by adding this empty post handler to the server:

```javascript
app.post("/liked", function (req, res) {
    //code goes here
   res.send("thanks");
});
```

Now you'll need to teach that new code to:

- [ ] check what value was sent through: try `console.log(req.body.postId);`
- [ ] Use that value to find the matching idea object in the ideas list. The code for this was done right at the end of #23 so look at that ticket.
- [ ] log that whole post to the console to make sure you've got it right. `console.log(idea)` or whatever
- [ ] when you find the matching post, increase its like counter: `idea.likes = idea.likes + 1`

# check it's working:

In your browser, look at http://localhost:3000/ideas to see how many likes each post has.

**Comment by mgatland** [comment]
consider doing #30 after this if there's any time left over
