### ISSUE TITLE
You can refresh the ideas list without refreshing the whole page

### ISSUE THREAD

**Issue by alicedilemma** [girlcodeakl/girlcodeapp#29]
Currently, the only way to refresh the ideas list is to refresh the whole page. Let's make a way to refresh the list whenever we want.

# A way to refresh the ideas list

in feed.html:
- [x] There is a line that makes a GET request and then calls createFeed. Move that line into a function called 'refreshIdeas'.
- [x] Call that function when the page first loads (so it still works as normal)
- [x] Add a link to the HTML with text 'refresh' that links to href="#". This makes it a link that does nothing.
- [x] Add a line to the JavaScript that uses jquery to select your link (you'll need to give it a class), then tells it to call your function on *click*.

For reference, look at the code in post.html that makes the form do something on 'submit'. Your line will be similar.

Test this. Does it work? did we forget anything...

Protip: if you wanted to delete the contents of an html element, you might do something like this:

`$(".idea-box").empty();`

# when to use this

When are some good times to refresh the list? Maybe when someone posts a new idea, or likes a post, the list should refresh immediately? Can you make it do this?

**Comment by abur864** [comment]
refreshes page on submit
