### ISSUE TITLE
Pics feature: post.html should let you attach a picture to your post

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcodeapp#37]
Version 1 is, you enter a link on the post form in post.html

- [x] on post.html, add a new text input field inside the form. This is where the user can paste in the url of an image.
- [x] in post.html, add some javascript to send the new field to the server.
- [x] use the Chrome Developer Tools to check that it's posting the new value when you post.

(look at the code that sends the existing field to the server for reference.)

- [ ] on the server (index.js), make the function addIdea take an extra argument, the imagelink. It should save this into the image object just like the 'idea' value is saved.
- [ ] on the server, when the user posts an idea, it calls addIdea. This call now needs to include a second argument req.body.imagelink to save the image link.

- [ ] on the server, in addIdea, if imagelink is undefined, then set it to a default image. maybe this one: https://pbs.twimg.com/profile_images/447460759329460224/mt2UmwGG_400x400.jpeg

- [ ] TEST: restart the server, post some new ideas and check localhost:3000/ideas to see that the image links are included.

**Comment by MeghanRD** [comment]
Doesn't let you change image even with a link.

**Comment by MeghanRD** [comment]
Alright, nevermind.
