### ISSUE TITLE
Put links on every page so it's easy to navigate between pages

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcodeapp#4]
As a user, I don't like having to remember all the URLs and type them in by hand.

I'd like to be able to click on links to get to every page on the site, and never get stuck on a page with no links.

- [ ] Make some HTML to add a list of links to all the pages in the site
- [ ] Add CSS to the style.css file to make the links appear as a bar going across the page instead of a list going down the page. You may need to put the links in a div with a new class, i.e. `<div class="nav-bar">`
- [ ] Add the HTML to every page
- [ ] check it works on every page

(This is often called the 'navigation bar' or 'nav bar')

**Comment by mgatland** [comment]
this is what a navigation bar looks like

![screen shot 2015-08-20 at 1 20 13 pm](https://cloud.githubusercontent.com/assets/364886/9373422/5f46085e-473e-11e5-9bb8-9aa4e33ca0e5.png)

**Comment by felEvs** [comment]
Do you guys still want a navigation bar? I'll reopen just in case :+1:

**Comment by mgatland** [comment]
closed as there's a new ticket for the remaining work
