### ISSUE TITLE
Save and display the author of each idea

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcodeapp#5]
Only take this ticket if #4 and #2 are done

### Act 1
- [x] in post.html, add a new `<input>` field to the form where the user can write their name. So there will be a field for your idea and a field for your name.
- [x] Make sure your new `<input>` field has a unique class name.
- [x] Check: open localhost:300/post.html and check your new input field appears on the form.

### Act 2
Now we need to send the author text to the server when they click 'submit'.
- [x] Look at the instructions for issue #2. Note how we get a value out of an input, and how we add it to the `data` object so it will be sent to the server.
- [x] Now make it so when the user clicks 'submit', the author text is added to the data object and sent to the server. You will need to add one line to the javascript in post.html. This will be very similar to the line that adds the idea text to the data object... 

### Act 3
Now it's (hopefully) being sent to the server, we need to teach the server to look out for this new information.
- [x] We're now working in server.js
- [x] find for the code that is run when a user POSTS a new idea to the server.
- [x] there is a line that writes the idea text to the console using `console.log(req.body.idea);`. Add another line that logs req.body.author as well. ('author' needs to match whatever you saved it as in the data object back in feed.html)
- [x] Restart the server, submit a new idea and check that your author name now shows up in terminal/command prompt.
- [x] If the author name is coming through, we can now save it. You do this by setting a new new name-value pair on the idea object that stores the author's name. Look at issue #4 for more on name-value pairs.

### Act 4
- [x] modify feed.html so it displays the author's name as well as the idea's text, in each post.

### notes

This task does not include updating the CSS look + feel of the post.html page. Just make it work, don't focus on making it pretty in this ticket.

**Comment by abur864** [comment]
Completed
