### ISSUE TITLE
Save the author of each idea

### ISSUE THREAD

**Issue by mgatland** [girlcodeakl/girlcodeapp#6]
Only do this after issue #5 and #11 are closed

- [x] In index.js, when you are saving an idea that someone posted, create a new name-value pair on the idea object that stores the author's name. You can get the author's name from their cookie. Look at #11 for more info on cookies, and issue #5  for more on name-value pairs. 
- [x] modify the feed.html so it displays the author's name next to each post.

- [x] if the user hasn't logged in (i.e. the cookie is undefined), then set the author to "anonymous"

This task does not include updating the look + feel of the post.html page - someone else will be working on that, so just add the parts you need and don't focus on the presentation too much.

**Comment by mgatland** [comment]
This task does not include updating the look + feel of the post.html page - someone else will be working on that, so just add the parts you need and don't focus on the presentation too much.

**Comment by felEvs** [comment]
i think pretty much everything is done! we just might need to put everything onto the master branch :+1:
